import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {randomUUID,createHash} from 'node:crypto';import Papa from 'papaparse';
function fixture(){
 let rows=[['coleccion','id','datos_json']],busy=false,failCommit=false,active='admin@example.test',writes=0;
 const cache=new Map(),props=new Map([['SPREADSHEET_ID','test-sheet'],['ADMIN_EMAILS','admin@example.test']]);
 const sheet={getSheetId:()=>1,getLastRow:()=>rows.length,getMaxRows:()=>10000,getRange:(row,col,n,width)=>({getValues:()=>rows.slice(row-1,row-1+n).map(r=>r.slice(col-1,col-1+width))})};
 const context=vm.createContext({console,Map,Date,JSON,Error,Utilities:{getUuid:randomUUID,DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>Array.from(createHash('sha256').update(s).digest()),parseCsv:s=>Papa.parse(s).data},Session:{getActiveUser:()=>({getEmail:()=>active}),getEffectiveUser:()=>({getEmail:()=> 'owner@example.test'})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v)})},CacheService:{getScriptCache:()=>({get:k=>cache.get(k)||null,put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k)})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet})},LockService:{getScriptLock:()=>({tryLock:()=>{if(busy)return false;busy=true;return true;},releaseLock:()=>{busy=false;}})},Sheets:{Spreadsheets:{batchUpdate:({requests})=>{if(failCommit)throw new Error('simulated quota error');const next=structuredClone(rows);for(const r of requests){if(r.updateCells){const i=r.updateCells.start.rowIndex;while(next.length<=i)next.push(['','','']);next[i]=r.updateCells.rows[0].values.map(v=>v.userEnteredValue.stringValue);}}rows=next;writes++;}}}});
 vm.runInContext(readFileSync('apps-script/Engine.gs','utf8')+'\n'+readFileSync('apps-script/Code.gs','utf8'),context);
 const engine=context.buildEngine_();let store=context.createStore_();engine.initialize(store);store.commit();
 const admin=(action,data={})=>context.optativaAdmin(action,data);
 admin('admin.config',{registrationOpen:true});
 for(let i=0;i<100;i++)admin('admin.create',{codigo_estudiante:'TEST'+i,apellidos:'PRUEBA'+String(i).padStart(3,'0'),nombres:'ANA FICTICIA',seccion:'basica',nivel:'9no',paralelo:'A'});
 const publicCall=(action,data={},client='client-test-123456789')=>context.optativaPublic(action,data,client);
 const args=i=>{const found=publicCall('search',{seccion:'basica',nivel:'9no',query:'PRUEBA'+String(i).padStart(3,'0')},'client-search-'+String(i).padStart(8,'0'));assert.ok(Array.isArray(found),JSON.stringify(found));return {studentId:found[0].id,ticket:found[0].ticket,seccion:'basica',nivel:'9no',subjectId:'robotica_ia'};};
 return {context,admin,publicCall,args,get:(c,id)=>context.createStore_().get(c,id),rows:()=>rows,writes:()=>writes,setBusy:v=>{busy=v;},failCommit:v=>{failCommit=v;},setActive:v=>{active=v;}};
}
test('Apps Script: motor síncrono genera las 24 materias y búsqueda sin escribir la hoja',()=>{const f=fixture(),before=f.writes();const a=f.args(0);assert.equal(a.studentId,'TEST0');f.publicCall('status');assert.equal(f.writes(),before);assert.equal(f.context.createStore_().list('groups').length,24);});
test('Apps Script: 100 intentos modelados pasan por bloqueo y solo 25 se matriculan',()=>{const f=fixture();const inputs=Array.from({length:100},(_,i)=>f.args(i));let success=0,full=0;for(let i=0;i<100;i++){const r=f.publicCall('enroll',inputs[i],'client-enroll-'+String(i).padStart(8,'0'));if(r.enrollment)success++;if(r.error?.code==='FULL')full++;}assert.equal(success,25);assert.equal(full,75);assert.equal(f.get('groups','9no_robotica_ia').inscritos,25);assert.equal(f.context.createStore_().list('enrollments').length,25);});
test('Apps Script: bloqueo ocupado y error de escritura no generan matrícula parcial',()=>{const f=fixture(),a=f.args(0);f.setBusy(true);assert.equal(f.publicCall('enroll',a).error.code,'BUSY');f.setBusy(false);assert.equal(f.get('enrollments','TEST0'),null);f.failCommit(true);assert.equal(f.publicCall('enroll',a).error.code,'INTERNAL');assert.equal(f.get('groups','9no_robotica_ia').inscritos,0);assert.equal(f.get('enrollments','TEST0'),null);f.failCommit(false);assert.ok(f.publicCall('enroll',a).enrollment);assert.equal(f.publicCall('enroll',a).error.code,'ALREADY');});
test('Apps Script: admin usa identidad activa, jamás identidad del propietario del despliegue',()=>{const f=fixture();f.setActive('');assert.equal(f.admin('admin.students').error.code,'UNAUTHORIZED');assert.equal(f.publicCall('admin.config',{registrationOpen:false}).error.code,'FORBIDDEN');f.setActive('attacker@example.test');assert.equal(f.admin('admin.config',{registrationOpen:false}).error.code,'UNAUTHORIZED');assert.equal(f.get('config','registration').registrationOpen,true);});
test('Apps Script: cambiar materia actualiza ambas plazas y auditoría en un batch',()=>{const f=fixture();f.publicCall('enroll',f.args(0));const before=f.writes();const r=f.admin('admin.change',{studentId:'TEST0',seccion:'basica',nivel:'9no',subjectId:'multimedia'});assert.ok(r.enrollment);assert.equal(f.writes(),before+1);assert.equal(f.get('groups','9no_robotica_ia').inscritos,0);assert.equal(f.get('groups','9no_multimedia').inscritos,1);});
test('Apps Script: importar nombre completo sin inventar separación',()=>{const f=fixture();const csv='codigo_estudiante,apellidos,nombres,seccion,nivel,paralelo,nombreCompleto\nEXCEL1,,,basica,8vo,A,APELLIDOS COMPUESTOS NOMBRE COMPLETO';assert.equal(f.admin('admin.importPreview',{csv}).validos,1);assert.equal(f.admin('admin.import',{csv}).importados,1);assert.equal(f.get('students','EXCEL1').nombreSinSeparar,true);});
