import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {SQLiteStore} from '../server/sqlite.mjs';import {initialize,dispatch,importStudents,parseImport,csvText} from '../server/service.mjs';import {changeEnrollment} from '../server/domain.mjs';import {normalize} from '../server/catalog.mjs';
async function fixture(n=110){
 const store=new SQLiteStore();await initialize(store);
 await store.transaction(async tx=>{tx.set('config','registration',{registrationOpen:true});for(let i=0;i<n;i++){const sid='S'+i;tx.set('students',sid,{id:sid,codigo_estudiante:sid,nombreCompleto:'MUÑOZ PÉREZ ANA '+i,nombreNormalizado:normalize('MUÑOZ PÉREZ ANA '+i),seccion:'basica',nivel:'9no',paralelo:'A',matriculado:false});}});
 const args=async(i,subjectId='robotica_ia')=>{const ticket=randomUUID();await store.transaction(async tx=>tx.set('tickets',ticket,{studentId:'S'+i,seccion:'basica',nivel:'9no',expiresAt:Date.now()+60000}));return {studentId:'S'+i,seccion:'basica',nivel:'9no',subjectId,ticket};};
 return {store,args};
}
test('1. estudiante válido registra matrícula y actualiza todos los datos',async()=>{const {store,args}=await fixture();const r=await changeEnrollment(store,await args(0));assert.equal(r.enrollment.subjectId,'robotica_ia');assert.equal((await store.get('groups','9no_robotica_ia')).inscritos,1);assert.equal((await store.get('students','S0')).matriculado,true);store.close();});
test('2. segunda matrícula rechazada',async()=>{const {store,args}=await fixture();await changeEnrollment(store,await args(0));await assert.rejects(changeEnrollment(store,await args(0,'multimedia')),{code:'ALREADY'});store.close();});
test('3. grupo lleno rechaza y no deja escrituras parciales',async()=>{const {store,args}=await fixture();for(let i=0;i<25;i++)await changeEnrollment(store,await args(i));await assert.rejects(changeEnrollment(store,await args(26)),{code:'FULL'});assert.equal(await store.get('enrollments','S26'),null);assert.equal((await store.get('students','S26')).matriculado,false);store.close();});
test('4. dos solicitudes disputan cupo 25: solo una gana',async()=>{const {store,args}=await fixture();for(let i=0;i<24;i++)await changeEnrollment(store,await args(i));const inputs=await Promise.all([args(24),args(25)]);const r=await Promise.allSettled(inputs.map(a=>changeEnrollment(store,a)));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await store.get('groups','9no_robotica_ia')).inscritos,25);store.close();});
test('5. 100 solicitudes simultáneas, 25 plazas y contadores consistentes',async()=>{const {store,args}=await fixture();const inputs=await Promise.all(Array.from({length:100},(_,i)=>args(i)));const r=await Promise.allSettled(inputs.map(a=>changeEnrollment(store,a)));assert.equal(r.filter(x=>x.status==='fulfilled').length,25);const es=await store.list('enrollments');for(const g of await store.list('groups')){assert.ok(g.inscritos<=25);assert.equal(g.inscritos,es.filter(e=>e.groupId===g.id).length);}store.close();});
test('6. subjectId manipulado rechazado',async()=>{const {store,args}=await fixture();await assert.rejects(changeEnrollment(store,await args(0,'inventada')),{code:'INVALID_SUBJECT'});await assert.rejects(changeEnrollment(store,await args(0,'../robotica_ia')),{code:'INVALID_ID'});store.close();});
test('7. materia de otra sección rechazada',async()=>{const {store,args}=await fixture();await assert.rejects(changeEnrollment(store,await args(0,'video_mapping')),{code:'INVALID_SUBJECT'});store.close();});
test('8. estudiante de otro nivel rechazado',async()=>{const {store,args}=await fixture();const a=await args(0);await store.transaction(async tx=>tx.set('students','S0',{...await tx.get('students','S0'),nivel:'8vo'}));await assert.rejects(changeEnrollment(store,a),{code:'INVALID_STUDENT'});store.close();});
test('9. cambio administrativo mantiene contadores y auditoría',async()=>{const {store,args}=await fixture();await changeEnrollment(store,await args(0));await changeEnrollment(store,await args(0,'produccion_musical'),'admin');assert.equal((await store.get('groups','9no_robotica_ia')).inscritos,0);assert.equal((await store.get('groups','9no_produccion_musical')).inscritos,1);assert.equal((await store.list('audit')).length,1);await changeEnrollment(store,{...await args(0),subjectId:null},'admin');assert.equal((await store.get('groups','9no_produccion_musical')).inscritos,0);assert.equal(await store.get('enrollments','S0'),null);store.close();});
test('10. múltiples clics/pestañas: una sola matrícula',async()=>{const {store,args}=await fixture();const a=await args(0);const r=await Promise.allSettled(Array.from({length:15},()=>changeEnrollment(store,a)));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await store.list('enrollments')).length,1);store.close();});
test('cierre, ticket alterado y autorización administrativa',async()=>{const {store,args}=await fixture();const a=await args(0);await assert.rejects(changeEnrollment(store,{...a,ticket:randomUUID()}),{code:'EXPIRED'});await store.transaction(async tx=>tx.set('config','registration',{registrationOpen:false}));await assert.rejects(changeEnrollment(store,a),{code:'CLOSED'});await assert.rejects(dispatch(store,'admin.students',{},{}),{code:'UNAUTHORIZED'});store.close();});
test('normalización, búsqueda limitada y privada',async()=>{const {store}=await fixture();assert.equal(normalize('  MUÑOZ  '),'munoz');const r=await dispatch(store,'search',{seccion:'basica',nivel:'9no',query:'Muñoz'},{ip:'test'});assert.equal(r.length,6);assert.equal(r[0].matriculado,undefined);assert.equal(r[0].codigo_estudiante,undefined);assert.equal((await dispatch(store,'search',{seccion:'basica',nivel:'8vo',query:'munoz'},{ip:'test'})).length,0);await assert.rejects(dispatch(store,'search',{seccion:'basica',nivel:'9no',query:'Mu'},{ip:'test'}),{code:'SHORT_QUERY'});store.close();});
test('CSV: comillas, duplicados, errores, fórmulas y reimportación segura',async()=>{const {store}=await fixture();const csv='codigo_estudiante,apellidos,nombres,seccion,nivel,paralelo\nNEW,GARCÍA LÓPEZ,ANA MARÍA,Básica Superior,8vo,A\nNEW,GARCÍA LÓPEZ,ANA MARÍA,Básica Superior,8vo,A';const p=parseImport(csv);assert.equal(p.duplicates,1);assert.equal(p.valid.length,1);await importStudents(store,p.valid,'admin');const r=await importStudents(store,p.valid,'admin');assert.equal(r.duplicados,1);assert.equal(parseImport('codigo_estudiante,apellidos,nombres,seccion,nivel,paralelo\nBAD,,,basica,8vo,A').errors.length,1);assert.ok(csvText([{name:'=1+1'}]).includes("'=1+1"));store.close();});
test('cambio a grupo lleno conserva matrícula y ambos contadores',async()=>{const {store,args}=await fixture();for(let i=0;i<25;i++)await changeEnrollment(store,await args(i));await changeEnrollment(store,await args(30,'multimedia'));await assert.rejects(changeEnrollment(store,await args(30),'admin'),{code:'FULL'});assert.equal((await store.get('enrollments','S30')).subjectId,'multimedia');assert.equal((await store.get('groups','9no_multimedia')).inscritos,1);assert.equal((await store.get('groups','9no_robotica_ia')).inscritos,25);store.close();});
