import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,ArrowLeft,GraduationCap,BookOpen,Check,Search,ShieldCheck,Camera,Bot,Sparkles,Music,Projector,Blocks,PenTool,Lock,LogOut,LayoutDashboard,Users,Upload,Download,History,X,CheckCircle2,AlertCircle} from 'lucide-react';
import {api,subscribeStatus,cloudMode,sheetsMode} from './api.js';
import {levels,sections,subjects} from '../server/catalog.mjs';
import './styles.css';
import {SheetsHost} from './SheetsHost.jsx';
const icons={Camera,Bot,Sparkles,Music,Projector,Blocks,PenTool};
const homeUrl=window.OPTATIVAS_HOME_URL||import.meta.env.BASE_URL;
const adminUrl=homeUrl+'?admin=1';
const date=x=>x?new Intl.DateTimeFormat('es-EC',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Guayaquil'}).format(new Date(x)):'—';
const subjectName=id=>subjects.find(s=>s.id===id)?.nombre||'Sin matrícula';
function ErrorBox({message}){return message?<div className="notice error" role="alert"><AlertCircle size={20}/><span>{message}</span></div>:null;}
function Brand(){return <a href={homeUrl} className="brand" aria-label="Eight Academy, inicio"><span className="brand-mark">8<span>•</span></span><span>EIGHT <b>ACADEMY</b><small>CREA TU PROPIO CAMINO</small></span></a>;}
function Modal({title,children,onClose,busy=false}){
 const ref=useRef();useEffect(()=>{const d=ref.current;d.showModal();return()=>d.close();},[]);
 return <dialog ref={ref} onCancel={e=>{e.preventDefault();if(!busy)onClose();}} aria-labelledby="dialog-title"><div className="modal-top"><span className="eyebrow">ANTES DE CONTINUAR</span><button className="icon-button" onClick={onClose} disabled={busy} aria-label="Cerrar"><X/></button></div><h2 id="dialog-title">{title}</h2>{children}</dialog>;
}
function StudentApp(){
 const [state,setState]=useState({config:null,groups:[]}),[connection,setConnection]=useState(''),[section,setSection]=useState(''),[level,setLevel]=useState(''),[query,setQuery]=useState(''),[matches,setMatches]=useState([]),[searching,setSearching]=useState(false),[searched,setSearched]=useState(false),[selected,setSelected]=useState(null),[receipt,setReceipt]=useState(null),[already,setAlready]=useState(false),[choice,setChoice]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const requestVersion=useRef(0),sending=useRef(false),heading=useRef(null);
 useEffect(()=>subscribeStatus(s=>{setState(s);setConnection('');},()=>setConnection('No pudimos actualizar los cupos. Comprueba tu conexión.')),[]);
 const step=receipt?4:selected?3:level?2:section?1:0;
 useEffect(()=>{heading.current?.focus();},[step]);
 useEffect(()=>{
 let active=true;const version=++requestVersion.current;setMatches([]);setSearched(false);
 if(query.trim().length<4||!section||!level||selected){setSearching(false);return;}
 setSearching(true);const timer=setTimeout(()=>api('search',{seccion:section,nivel:level,query}).then(v=>{if(active&&version===requestVersion.current){setMatches(v);setSearched(true);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setSearching(false);}),350);
 return()=>{active=false;clearTimeout(timer);};
 },[query,section,level,selected]);
 const reset=()=>{requestVersion.current++;setSection('');setLevel('');setQuery('');setSelected(null);setReceipt(null);setChoice(null);setError('');setAlready(false);setMatches([]);};
 useEffect(()=>{if(!selected&&!query)return;let timeout;const activity=()=>{clearTimeout(timeout);timeout=setTimeout(reset,300000);};activity();window.addEventListener('pointerdown',activity);window.addEventListener('keydown',activity);return()=>{clearTimeout(timeout);window.removeEventListener('pointerdown',activity);window.removeEventListener('keydown',activity);};},[selected,query]);
 async function select(s){if(sending.current)return;sending.current=true;setBusy(true);setError('');try{const r=await api('select',{studentId:s.id,ticket:s.ticket,seccion:section,nivel:level});setSelected({...s,...r.student});setMatches([]);if(r.enrollment){setReceipt(r);setAlready(true);}}catch(e){setError(e.message);}finally{sending.current=false;setBusy(false);}}
 async function confirm(){if(sending.current)return;sending.current=true;setBusy(true);setError('');try{
 const r=await api('enroll',{studentId:selected.id,ticket:selected.ticket,seccion:section,nivel:level,subjectId:choice.id});setReceipt(r);setChoice(null);
 }catch(e){setChoice(null);setError(e.message);if(e.code==='ALREADY'){try{const r=await api('select',{studentId:selected.id,ticket:selected.ticket,seccion:section,nivel:level});setReceipt(r);setAlready(true);}catch{}}if(e.code==='EXPIRED'){setSelected(null);setQuery('');}try{setState(await api('status'));}catch{}
 }finally{sending.current=false;setBusy(false);}}
 const open=state.config?.registrationOpen&&(!state.config.fechaInicio||Date.now()>=Date.parse(state.config.fechaInicio))&&(!state.config.fechaFin||Date.now()<=Date.parse(state.config.fechaFin));
 const goBack=()=>{setError('');if(selected){setSelected(null);setQuery('');}else if(level){setLevel('');setQuery('');}else setSection('');};
 return <div className="student-shell"><header><Brand/><div className="header-right"><span className="year">AÑO LECTIVO 2026–2027</span><a className="admin-link" href={adminUrl}><Lock size={14}/> Administración</a></div></header>
 <main className="student-main"><div className="intro"><span className="eyebrow">PROGRAMA DE MATERIAS OPTATIVAS</span><h1>Tu curiosidad.<br/><em>Tu próxima elección.</em></h1><p>Selecciona tu materia optativa para este año lectivo.</p></div>
 <nav className="stepper" aria-label="Progreso de inscripción">{['Sección','Nivel','Estudiante','Materia','Confirmación'].map((s,i)=><div key={s} className={i<step?'done':i===step?'active':''} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={15}/>:i+1}</span><b>{s}</b></div>)}</nav>
 <ErrorBox message={connection||error}/>
 {!state.config?<div className="panel">Cargando disponibilidad…</div>:!open&&!receipt?<div className="panel closed"><Lock size={36}/><h2>{state.config.setupPending?'Inscripciones en preparación':'Inscripciones cerradas'}</h2><p>{state.config.setupPending?'El registro en línea todavía no está habilitado.':'El proceso de selección de materias optativas se encuentra cerrado.'}</p><p>Tu colegio te informará cuándo puedes realizar tu elección.</p></div>:receipt?<section className="panel receipt"><span className="success-icon"><CheckCircle2 size={40}/></span><span className="eyebrow">{already?'ELECCIÓN EXISTENTE':'MATRÍCULA REGISTRADA'}</span><h2 ref={heading} tabIndex="-1">{already?'Ya realizaste tu elección de materia optativa.':'¡Ya tienes tu próxima aventura!'}</h2><p>{already?'Esta es la materia que tienes asignada.':'Tu elección ha sido registrada correctamente.'}</p><dl><div><dt>Estudiante</dt><dd>{receipt.student.nombreCompleto}</dd></div><div><dt>Nivel y paralelo</dt><dd>{receipt.student.nivel} {receipt.student.paralelo}</dd></div><div><dt>Materia seleccionada</dt><dd>{subjectName(receipt.enrollment.subjectId)}</dd></div><div><dt>Fecha de registro</dt><dd>{date(receipt.enrollment.fechaRegistro)}</dd></div></dl><button className="primary" onClick={reset}>Finalizar <Check size={18}/></button><small>Al finalizar, tus datos se borrarán de esta pantalla.</small></section>:<>
 <div className="section-title"><div><span className="eyebrow">PASO {step+1} DE 5</span><h2 ref={heading} tabIndex="-1">{['¿En qué sección estás?','Selecciona tu nivel','Vamos a encontrar tu nombre','¿Qué te gustaría explorar?'][step]}</h2><p>{['Selecciona tu sección para ver las opciones disponibles.','Solo verás las materias correspondientes a tu nivel.','Escribe tus apellidos completos y selecciona tu nombre.','Elige una de las cuatro materias. Tienes 25 cupos por materia.'][step]}</p></div>{step>0&&<button className="text-button" onClick={goBack} disabled={busy}><ArrowLeft size={17}/> Volver</button>}</div>
 {step===0&&<div className="section-cards">{Object.entries(sections).map(([id,label],i)=><button key={id} className={'section-card '+id} onClick={()=>setSection(id)}><div className="card-top"><span className="section-icon">{i?<GraduationCap size={32}/>:<BookOpen size={32}/>}</span><span className="mini-label">3 NIVELES</span></div><h3>{label}</h3><p>{i?'1ero, 2do y 3ro BGU':'8vo, 9no y 10mo'}</p><div className="card-bottom"><span>Explora tus posibilidades</span><span className="round-arrow"><ArrowRight size={21}/></span></div></button>)}</div>}
 {step===1&&<div className="level-cards">{levels[section].map((l,i)=><button className="level-card" key={l} onClick={()=>setLevel(l)}><span className="eyebrow">{sections[section]}</span><h3>{l}</h3><span>Seleccionar nivel <ArrowRight size={20}/></span></button>)}</div>}
 {step===2&&<div className="panel search-panel"><div className="breadcrumb">{sections[section]} <span>/</span> {level}</div><label htmlFor="student-search">Escribe tus apellidos completos</label><div className="search-box"><Search size={21}/><input id="student-search" autoComplete="off" placeholder="Por ejemplo: García López" value={query} onChange={e=>setQuery(e.target.value)} aria-describedby="search-help" aria-controls="search-results"/></div><p id="search-help" className="hint">Escribe al menos 4 caracteres. No necesitas tildes ni mayúsculas.</p><div aria-live="polite">{searching?'Buscando estudiantes…':searched&&!matches.length?'No encontramos estudiantes con esos apellidos. Revisa tu nivel o escribe el primer apellido.':''}</div><ul id="search-results" className="results">{matches.map(s=><li key={s.id}><button onClick={()=>select(s)} disabled={busy}><span><strong>{s.nombreCompleto}</strong><small>{s.nivel} · Paralelo {s.paralelo}</small></span><ArrowRight size={20}/></button></li>)}</ul><div className="privacy"><ShieldCheck size={18}/><span>Selecciona únicamente tu nombre. Si no aparece, consulta a tu docente.</span></div></div>}
 {step===3&&<><div className="student-chip"><span className="avatar">{selected.nombreCompleto.slice(0,1)}</span><span><strong>{selected.nombreCompleto}</strong><small>{selected.nivel} · Paralelo {selected.paralelo}</small></span><span className="live-label">Cupos actualizados</span></div><div className="subject-grid">{subjects.filter(s=>s.secciones.includes(section)).map(s=>{const g=state.groups.find(g=>g.nivel===level&&g.subjectId===s.id);const free=g?25-g.inscritos:0,Icon=icons[s.icon];return <article key={s.id} className={'subject-card '+s.color}><div className="subject-top"><span className="subject-icon"><Icon size={26}/></span><span className={'badge '+(free>10?'green':free?'yellow':'red')}>{free?free+' cupos disponibles':'Cupo agotado'}</span></div><h3>{s.nombre}</h3><p>{s.descripcion}</p><div className="capacity"><span>{g?.inscritos??'—'} / 25 inscritos</span><div><i style={{width:(g?.inscritos||0)*4+'%'}}/></div></div><button className="choose" disabled={!g||free===0||busy||!!connection} onClick={()=>setChoice(s)}>{free?'Elegir materia':'Cupo agotado'}<ArrowRight size={18}/></button></article>;})}</div><div className="privacy centered"><ShieldCheck size={18}/> Tu elección será definitiva. Revisa tu materia antes de confirmar.</div></>}
 </>}
 <div className="bottom-note"><span><BookOpen size={17}/> Una materia. Muchas posibilidades.</span><span>¿Necesitas ayuda? Consulta a tu docente.</span></div></main>
 <footer><span>© 2026 Eight Academy</span><span>Aprender también es elegir.</span></footer>
 {choice&&<Modal title="Confirma tu elección" busy={busy} onClose={()=>setChoice(null)}><p>Estás por seleccionar:</p><div className="confirmation-choice"><strong>{choice.nombre}</strong><span>Nivel: {level}</span></div><p>Esta elección será definitiva y no podrás seleccionar otra materia desde este sistema.</p><p><b>¿Deseas confirmar?</b></p><div className="modal-actions"><button className="secondary" onClick={()=>setChoice(null)} disabled={busy}>Cancelar</button><button className="primary" onClick={confirm} disabled={busy}>{busy?'Registrando…':'Confirmar matrícula'}</button></div></Modal>}
 </div>;
}
function AdminApp(){
 const [authed,setAuthed]=useState(false),[loading,setLoading]=useState(true),[tab,setTab]=useState('dashboard'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[dashboard,setDashboard]=useState(null),[students,setStudents]=useState({rows:[],total:0}),[filters,setFilters]=useState({page:0}),[audit,setAudit]=useState([]),[csv,setCsv]=useState(''),[preview,setPreview]=useState(null),[editing,setEditing]=useState(null),[newSubject,setNewSubject]=useState(''),[refresh,setRefresh]=useState(0);
 const lock=useRef(false);
 async function work(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message);if(e.code==='UNAUTHORIZED')setAuthed(false);}finally{lock.current=false;setBusy(false);}}
 useEffect(()=>{api('session').then(s=>setAuthed(s.admin)).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!authed)return;let active=true;api('admin.dashboard').then(x=>{if(active)setDashboard(x);}).catch(e=>{if(active)setError(e.message);});const timer=setInterval(()=>setRefresh(r=>r+1),10000);return()=>{active=false;clearInterval(timer);};},[authed,refresh]);
 useEffect(()=>{if(!authed)return;let active=true;const timer=setTimeout(()=>{if(tab==='students')api('admin.students',filters).then(v=>{if(active)setStudents(v);}).catch(e=>{if(active)setError(e.message);});if(tab==='audit')api('admin.audit').then(v=>{if(active)setAudit(v);}).catch(e=>{if(active)setError(e.message);});},250);return()=>{active=false;clearTimeout(timer);};},[authed,tab,filters,refresh]);
 const updateFilter=(k,v)=>setFilters(f=>({...f,page:0,[k]:v,...(k==='seccion'?{nivel:''}:{})}));
 async function download(type){await work(async()=>{const {csv}=await api('admin.export',{type});const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='optativas-'+type+'.csv';a.click();URL.revokeObjectURL(url);});}
 if(loading)return <main className="login-panel">Comprobando sesión…</main>;
 if(!authed&&sheetsMode)return <main className="login-shell"><div className="panel"><h1>Administración</h1><p>Abre la hoja privada con tu cuenta de Google y selecciona <b>Optativas → Abrir panel administrativo</b>.</p><ErrorBox message={error}/><a href={homeUrl}>Volver a inscripción</a></div></main>;
 if(!authed)return <div className="login-shell"><Brand/><form className="panel login-panel" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));work(async()=>{await api('login',d);setAuthed(true);});}}><span className="section-icon"><ShieldCheck size={28}/></span><h1>Administración</h1><p>Acceso exclusivo para el equipo del colegio.</p><ErrorBox message={error}/>{cloudMode&&<label>Correo electrónico<input type="email" name="email" autoComplete="username" required/></label>}<label>Contraseña<input type="password" name="password" autoComplete="current-password" required/></label><button className="primary" disabled={busy}>{busy?'Ingresando…':'Ingresar al panel'}<ArrowRight size={18}/></button><a href={homeUrl}>Volver a inscripción</a></form></div>;
 return <div className="admin-shell"><aside><Brand/><div className="admin-caption">GESTIÓN ACADÉMICA</div><nav>{[['dashboard',LayoutDashboard,'Resumen'],['students',Users,'Estudiantes'],['import',Upload,'Cargar nómina'],['exports',Download,'Reportes'],['audit',History,'Auditoría']].map(([key,Icon,label])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setError('');setMessage('');}}><Icon size={19}/>{label}</button>)}</nav><div className="sidebar-bottom"><a href={homeUrl} target="_blank" rel="noreferrer">Ver inscripción <ArrowRight size={16}/></a><button onClick={()=>work(async()=>{await api('logout');setAuthed(false);})}><LogOut size={18}/>{sheetsMode?'Salir del panel':'Cerrar sesión'}</button></div></aside>
 <main className="admin-main"><div className="admin-heading"><div><span className="eyebrow">EIGHT ACADEMY · 2026–2027</span><h1>{({dashboard:'Resumen de inscripciones',students:'Estudiantes',import:'Cargar nómina',exports:'Reportes y descargas',audit:'Auditoría'})[tab]}</h1></div><span className={'badge '+(dashboard?.config.registrationOpen?'green':'red')}>{dashboard?.config.registrationOpen?'Inscripciones abiertas':'Inscripciones cerradas'}</span></div><ErrorBox message={error}/>{message&&<div className="notice success" role="status">{message}</div>}
 {tab==='dashboard'&&dashboard&&<><div className="stats"><div><span>Estudiantes en nómina</span><strong>{dashboard.total}</strong></div><div><span>Matrículas registradas</span><strong>{dashboard.enrolled}</strong></div><div><span>Pendientes de elegir</span><strong>{dashboard.total-dashboard.enrolled}</strong></div><div><span>Cupos disponibles</span><strong>{600-dashboard.enrolled}</strong></div></div>
 {Object.entries(dashboard.byLevel).filter(([,v])=>v>100).map(([l,v])=><div key={l} className="notice warning"><AlertCircle/><span><strong>{l}: {v} estudiantes para 100 cupos.</strong> La capacidad actual no permite matricular a todo el nivel. El límite por materia se mantiene en 25.</span></div>)}
 <div className="panel registration-control"><div><h3>Proceso de inscripción</h3><p>{dashboard.config.registrationOpen?'Los estudiantes pueden realizar su elección.':'Abre el proceso cuando la nómina esté revisada.'}</p></div><button className={dashboard.config.registrationOpen?'secondary':'primary'} disabled={busy} onClick={()=>work(async()=>{await api('admin.config',{...dashboard.config,registrationOpen:!dashboard.config.registrationOpen});setRefresh(r=>r+1);})}>{dashboard.config.registrationOpen?'Cerrar inscripciones':'Abrir inscripciones'}</button></div>
 <div className="dashboard-grid">{Object.values(levels).flat().map(l=><section className="panel level-summary" key={l}><div><h3>{l}</h3><span>{dashboard.byLevel[l]} estudiantes</span></div>{dashboard.groups.filter(g=>g.nivel===l).map(g=><div className="group-row" key={g.id}><span>{g.nombre}</span><strong className={g.inscritos===25?'full':''}>{g.inscritos}<small>/25</small></strong><div className="meter"><i style={{width:g.inscritos*4+'%'}}/></div></div>)}</section>)}</div></>}
 {tab==='students'&&<><div className="panel filters"><label>Buscar<input placeholder="Nombre o código" value={filters.query||''} onChange={e=>updateFilter('query',e.target.value)}/></label><label>Sección<select value={filters.seccion||''} onChange={e=>updateFilter('seccion',e.target.value)}><option value="">Todas</option>{Object.entries(sections).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Nivel<select value={filters.nivel||''} onChange={e=>updateFilter('nivel',e.target.value)}><option value="">Todos</option>{(filters.seccion?levels[filters.seccion]:Object.values(levels).flat()).map(l=><option key={l}>{l}</option>)}</select></label><label>Paralelo<select value={filters.paralelo||''} onChange={e=>updateFilter('paralelo',e.target.value)}><option value="">Todos</option>{['A','B','C','D'].map(p=><option key={p}>{p}</option>)}</select></label><label>Materia<select value={filters.subjectId||''} onChange={e=>updateFilter('subjectId',e.target.value)}><option value="">Todas</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={!!filters.unenrolled} onChange={e=>updateFilter('unenrolled',e.target.checked)}/> Sin matrícula</label></div>
 <div className="panel table-panel"><div className="table-heading"><b>{students.total} estudiantes</b><button className="primary" onClick={()=>setEditing({new:true})}>Registrar estudiante</button></div><div className="table-scroll"><table><thead><tr><th>Estudiante</th><th>Nivel</th><th>Materia asignada</th><th>Acciones</th></tr></thead><tbody>{students.rows.map(s=><tr key={s.id}><td><strong>{s.nombreCompleto}</strong><small>{s.id}</small></td><td>{s.nivel} {s.paralelo}</td><td>{subjectName(s.materiaAsignada)}<small>{date(s.fechaMatricula)}</small></td><td><button className="text-button" onClick={()=>{setEditing(s);setNewSubject(s.materiaAsignada||'');}}>Gestionar</button></td></tr>)}</tbody></table></div>{!students.rows.length&&<p className="empty">No hay estudiantes con estos filtros.</p>}<div className="pagination"><button disabled={!filters.page} onClick={()=>setFilters(f=>({...f,page:f.page-1}))}>Anterior</button><span>Página {(filters.page||0)+1}</span><button disabled={((filters.page||0)+1)*50>=students.total} onClick={()=>setFilters(f=>({...f,page:(f.page||0)+1}))}>Siguiente</button></div></div></>}
 {tab==='import'&&<section className="panel import-panel"><Upload size={30}/><h2>Importar estudiantes desde CSV</h2><p>Primero revisa la vista previa. Los códigos existentes se omiten y las matrículas se conservan.</p><p className="hint">Columnas: codigo_estudiante, apellidos, nombres, seccion, nivel, paralelo.</p><label className="file-label">Selecciona un archivo CSV<input type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files[0];setPreview(null);setCsv('');if(f)work(async()=>{if(f.size>600000)throw new Error('El archivo supera 600 KB.');const text=await f.text();setCsv(text);setPreview(await api('admin.importPreview',{csv:text}));});}}/></label>{preview&&<><div className="stats"><div><span>Para importar</span><strong>{preview.validos}</strong></div><div><span>Duplicados</span><strong>{preview.duplicados}</strong></div><div><span>Con errores</span><strong>{preview.errors.length}</strong></div></div>{preview.errors.length>0?<ul>{preview.errors.map((e,i)=><li key={i}>Fila {e.fila}: {e.error}</li>)}</ul>:<><h3>Vista previa</h3><ul>{preview.muestra.map(s=><li key={s.id}>{s.nombreCompleto} · {s.nivel} {s.paralelo}</li>)}</ul><button className="primary" disabled={busy||!preview.validos} onClick={()=>work(async()=>{const r=await api('admin.import',{csv});setMessage('Importados: '+r.importados+' · Duplicados: '+r.duplicados+' · Errores: '+r.errores);setPreview(null);setCsv('');setRefresh(v=>v+1);})}>Confirmar importación</button></>}</>}</section>}
 {tab==='exports'&&<div className="report-grid">{[['students','Nómina y matrículas','Todos los estudiantes, su materia y fecha de registro.'],['groups','Inscritos por materia','Ocupación y cupos disponibles de cada grupo.'],['levels','Resumen por nivel','Matrículas, pendientes y cupos por nivel académico.'],['pending','Estudiantes sin matrícula','Nómina de estudiantes que todavía no han elegido.']].map(([key,title,description])=><div className="panel" key={key}><Download size={25}/><h2>{title}</h2><p>{description}</p><button className="secondary" disabled={busy} onClick={()=>download(key)}>Descargar CSV</button></div>)}</div>}
 {tab==='audit'&&<div className="panel table-panel"><p>Últimas 100 acciones administrativas</p><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Administrador</th><th>Acción</th><th>Estudiante</th><th>Detalle</th></tr></thead><tbody>{audit.map((a,i)=><tr key={i}><td>{date(a.fecha)}</td><td>{a.administrador}</td><td>{a.accion}</td><td>{a.estudiante||'—'}</td><td>{a.accion==='CAMBIO_MATERIA'||a.accion==='LIBERAR_MATRICULA'?subjectName(a.anterior?.subjectId)+' → '+subjectName(a.nuevo?.subjectId):a.accion==='CONFIGURACION'?(a.nuevo.registrationOpen?'Apertura':'Cierre'):'Alta de estudiante'}</td></tr>)}</tbody></table></div></div>}
 </main>{editing&&<Modal title={editing.new?'Registrar estudiante':'Gestionar matrícula'} busy={busy} onClose={()=>setEditing(null)}><ErrorBox message={error}/>{editing.new?<form onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));work(async()=>{const r=await api('admin.create',d);if(r.duplicados)throw new Error('Ese código ya existe.');setEditing(null);setMessage('Estudiante registrado.');setRefresh(r=>r+1);});}}><div className="form-grid">{[['codigo_estudiante','Código'],['apellidos','Apellidos'],['nombres','Nombres']].map(([name,label])=><label key={name}>{label}<input name={name} required maxLength={100}/></label>)}<label>Sección<select name="seccion" required onChange={e=>setEditing({...editing,seccion:e.target.value})} defaultValue=""><option value="" disabled>Seleccionar</option>{Object.entries(sections).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Nivel<select name="nivel" required>{(levels[editing.seccion]||[]).map(l=><option key={l}>{l}</option>)}</select></label><label>Paralelo<input name="paralelo" required pattern="[A-Z]{1,2}" maxLength={2}/></label></div><button className="primary" disabled={busy}>Registrar</button></form>:<><p><b>{editing.nombreCompleto}</b><br/>{editing.nivel} {editing.paralelo}</p><label>Materia<select value={newSubject} onChange={e=>setNewSubject(e.target.value)}><option value="">Liberar matrícula</option>{subjects.filter(s=>s.secciones.includes(editing.seccion)).map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select></label><p>El cambio actualizará los cupos y quedará registrado en auditoría.</p><button className="primary" disabled={busy} onClick={()=>work(async()=>{await api('admin.change',{studentId:editing.id,seccion:editing.seccion,nivel:editing.nivel,subjectId:newSubject||null});setEditing(null);setMessage('Matrícula actualizada.');setRefresh(r=>r+1);})}>Confirmar cambio</button></>}</Modal>}</div>;
}
const isAdmin=window.OPTATIVAS_ADMIN===true||new URLSearchParams(location.search).get('admin')==='1'||location.pathname===homeUrl+'admin';
createRoot(document.getElementById('root')).render(sheetsMode&&!window.google?.script?.run?<SheetsHost/>:isAdmin?<AdminApp/>:<StudentApp/>);
